name: Git Workshop Demo

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'

env:
  SERVER_IP: '127.0.0.1'
  COMPANY_NAME: 'I JET KKKKK'
  REPO_NAME: ${{github.repository}}

jobs:
  job-1:
    runs-on: ubuntu-latest
    environment: devolopment
    steps:
      - run: echo "CHECK ${{github.actor}}"
      - run: echo "Hello ${{env.COMPANY_NAME}}"
      - run: echo "repo ${{env.REPO_NAME}}"
      - run: echo "var ${{vars.APP_NAME}}"
      - run: echo "kuy ${{secrets.KEY_BOX}}"
  job-2:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Hello JOB 2 ${{env.COMPANY_NAME}}"
      - run: echo ${{env.SERVER_IP}}
      - run: echo ${{vars.PRODUCTION_NAME}}